### ISSUE TITLE
Abrir QR en navegador

### ISSUE THREAD

**Issue by djcesar** [ivanbtrujillo/Ionic-LectorQR#1]
Hola quisiera saber como puedo hacer para que al escanear el QR no muestre el texto, si no ejecute el navegador del dispositivo visualizando la url.

Que recomendación podrías dar? 

Gracias

**Comment by djcesar** [comment]
usar como resultado del scan `window.open(imagenEscaneada.text,'_system')` para abrir en el navegador nativo

**Comment by ivanbtrujillo** [comment]
Hola cesar. Si, puedes hacer eso o utilizar el plugin inappbrowser para que en vez de que te abra el navegador del sistema, visualizar la web que quieras en la propia vista de la APP. Te adjunto el plugin:

http://ngcordova.com/docs/plugins/inAppBrowser/

Gracias por el aporte para abrir el navegador nativo!,
